/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */



import scam.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTextPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nathan
 */
public class BillingUI extends javax.swing.JFrame {
    /**
     * Creates new form BillingUI
     */
    private Product selectedProduct;
    private DefaultTableModel billingModel;
    private final List<Product> billDataList = new ArrayList<>();
    
    public BillingUI(DefaultTableModel model) {
        String[] columnNames = {"ID", "Product", "Price", "Quantity", "Total Price"};
        billingModel = new DefaultTableModel(new Object[0][5], columnNames); // Empty model
        initComponents();
        inventoryTable.setModel(model); // Set the model for the inventory table
        billTable.setModel(billingModel); // Set it to the billTable
        setColumnWidths(); // Set the model for the inventory table
        setTableAlignment();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        inventoryTable = new javax.swing.JTable();
        billPanel = new javax.swing.JPanel();
        billLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        billTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cashier");

        inventoryTable.setModel(new DefaultTableModel());
        inventoryTable.setToolTipText("");
        inventoryTable.setShowGrid(true);
        inventoryTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inventoryTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(inventoryTable);
        inventoryTable.getAccessibleContext().setAccessibleName("");

        billPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        billLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        billLabel.setText("BILL");
        billLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        billTable.setModel(billingModel);
        billTable.setToolTipText("");
        billTable.setShowGrid(false);
        jScrollPane3.setViewportView(billTable);

        javax.swing.GroupLayout billPanelLayout = new javax.swing.GroupLayout(billPanel);
        billPanel.setLayout(billPanelLayout);
        billPanelLayout.setHorizontalGroup(
            billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billPanelLayout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(billLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );
        billPanelLayout.setVerticalGroup(
            billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(billLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextPane1.setToolTipText("");
        jScrollPane2.setViewportView(jTextPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jLabel1.setText("total:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(billPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(178, 178, 178))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(billPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    public void billingModel() {
        // Convert the list of selected products to a 2D array
        Object[][] billData = new Object[billDataList.size()][5];
        for (int i = 0; i < billDataList.size(); i++) {
            Product product = billDataList.get(i);
            billData[i][0] = product.getId();
            billData[i][1] = product.getName();
            billData[i][2] = product.getPrice();
            billData[i][3] = product.getQuantity();
            billData[i][4] = product.getTotalPrice();
            
        }

        // Create the model and set it to the bill table
        billingModel.setDataVector(billData, new String[] {"ID","Product", "Price","Quantity","Total Price"});
        billTable.setModel(billingModel);
        
    }

    
    private void inventoryTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryTableMouseClicked
        int selectedRow = inventoryTable.getSelectedRow();
    
        if (selectedRow != -1) {
            // Retrieve data from the selected row
            int id = (Integer) inventoryTable.getValueAt(selectedRow, 4);
            String productName = inventoryTable.getValueAt(selectedRow, 1).toString();
            String priceWithText = inventoryTable.getValueAt(selectedRow, 2).toString();
            double price = Double.parseDouble(priceWithText.split(" ")[0]); // Extract numeric part
            int quantity = 1;

            // Create a Product object
            selectedProduct = new Product(id, productName, price, quantity);
            
            // Add to bill data list
            billDataList.add(selectedProduct);
            billingModel();

            JTextPane textPane = jTextPane1;

            // Display the selected item's details
            System.out.print("ID:" + selectedProduct.getId() + " | ");
            System.out.print(selectedProduct.getName() + " | ");
            System.out.print(selectedProduct.getPrice() + " petot | ");
            System.out.print(selectedProduct.getQuantity() + " pc\n");

            StringBuilder sb = new StringBuilder();
            sb.append("ID:").append(selectedProduct.getId()).append(" | ");
            sb.append(selectedProduct.getName()).append(" | ");
            sb.append(selectedProduct.getPrice()).append(" petot |");
            sb.append(selectedProduct.getQuantity()).append(" pc");

            textPane.setText(sb.toString());
        }
    }//GEN-LAST:event_inventoryTableMouseClicked
    
    private void setColumnWidths() {
        inventoryTable.getColumnModel().getColumn(0).setPreferredWidth(30); // Index column
        inventoryTable.getColumnModel().getColumn(1).setPreferredWidth(200); // Product column
        inventoryTable.getColumnModel().getColumn(2).setPreferredWidth(80);  // Price column
        inventoryTable.getColumnModel().getColumn(3).setPreferredWidth(80);  // Quantity column
        inventoryTable.getColumnModel().getColumn(4).setPreferredWidth(50);  // ID column
    }
    
    private void setTableAlignment() {
    DefaultTableCellRenderer leftRenderer = new DefaultTableCellRenderer();
    DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
    leftRenderer.setHorizontalAlignment(SwingConstants.LEFT); // Align text to the left
    centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);

    // Assuming you have 4 columns
    inventoryTable.getColumnModel().getColumn(0).setCellRenderer(centerRenderer); // Index column
    inventoryTable.getColumnModel().getColumn(1).setCellRenderer(leftRenderer); // Product column
    inventoryTable.getColumnModel().getColumn(2).setCellRenderer(leftRenderer); // Price column
    inventoryTable.getColumnModel().getColumn(3).setCellRenderer(leftRenderer); // Quantity column
    inventoryTable.getColumnModel().getColumn(4).setCellRenderer(leftRenderer); // ID column
}
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel billLabel;
    private javax.swing.JPanel billPanel;
    private javax.swing.JTable billTable;
    private javax.swing.JTable inventoryTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
